---
   - name: Install openvpn
     become: yes
     apt: 
       name: openvpn
       state: latest

   - name: Install openvpn config
     become: yes
     template: 
       src: client.j2 
       dest: /etc/openvpn/client.conf

   - name: Run openvpn with config
     become: yes     
     service:
       name: openvpn@client
       state: started
       enabled: yes
